services:
  - docker
before_script:
  - set -e
  - if [[ "$TRAVIS_BRANCH" = "$DEFAULT_BRANCH" && "$TRAVIS_PULL_REQUEST" = "false" ]] || [ "$TRAVIS_BRANCH" = "$TRAVIS_TAG" ]; then
      DO_DOCKER="true";
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    fi
  - docker-compose -f docker-compose.lint-test.yml build
  - docker-compose -f docker-compose.build.yml run check
  - docker-compose -f docker-compose.build.yml run fmt
  - docker-compose -f docker-compose.build.yml run clippy
  - docker-compose -f docker-compose.build.yml run build-debug
  - docker-compose -f docker-compose.build.yml run build
  - docker-compose -f docker-compose.build.yml run clean
  - git reset --hard
script:
  - docker-compose -f docker-compose.lint-test.yml run lint-test

after_script:
  - if [ "$DO_DOCKER" = "true" ]; then
      docker push $DOCKER_USERNAME/rs-pgfs-report:$TRAVIS_BRANCH;
    fi

branches:
  only:
    - develop
notifications: null
email: false
